<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the comments table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-07-12 09:25:14
 */
class CommentsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('comments')->truncate();
        
        // Insert data in chunks
        DB::table('comments')->insert([
            [
                'id' => 1,
                'post_id' => 2,
                'user_id' => 2,
                'parent_id' => null,
                'content' => 'awesome!',
                'image_path' => null,
                'likes_count' => 1,
                'replies_count' => 0,
                'created_at' => '2026-07-12 08:57:39',
                'updated_at' => '2026-07-12 08:57:39',
            ],
            [
                'id' => 2,
                'post_id' => 3,
                'user_id' => 1,
                'parent_id' => null,
                'content' => 'Looks delicious',
                'image_path' => 'comments/XcamwcGVa5VD7zrJkVXpMys330XbRm5xubJFEGkk.png',
                'likes_count' => 0,
                'replies_count' => 0,
                'created_at' => '2026-07-12 09:18:13',
                'updated_at' => '2026-07-12 09:18:13',
            ],
            [
                'id' => 3,
                'post_id' => 4,
                'user_id' => 1,
                'parent_id' => null,
                'content' => 'Looks delicious',
                'image_path' => 'comments/uaUcg5c1axyX2BkH1mwmT7izvpPZjFnEinkD8iBx.png',
                'likes_count' => 0,
                'replies_count' => 0,
                'created_at' => '2026-07-12 09:18:58',
                'updated_at' => '2026-07-12 09:18:58',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}