<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the likes table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-07-12 09:25:14
 */
class LikesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('likes')->truncate();
        
        // Insert data in chunks
        DB::table('likes')->insert([
            // Post 2 (breakfast) — liked by users 1 and 3 → likes_count = 2
            [
                'user_id' => 1,
                'likeable_type' => 'App\Models\Post',
                'likeable_id' => 2,
                'created_at' => '2026-07-12 09:18:29',
                'updated_at' => '2026-07-12 09:18:29',
            ],
            [
                'user_id' => 3,
                'likeable_type' => 'App\Models\Post',
                'likeable_id' => 2,
                'created_at' => '2026-07-11 16:03:35',
                'updated_at' => '2026-07-11 16:03:35',
            ],
            // Post 3 (sunrise) — liked by user 6 → likes_count = 1
            [
                'user_id' => 6,
                'likeable_type' => 'App\Models\Post',
                'likeable_id' => 3,
                'created_at' => '2026-07-12 08:28:00',
                'updated_at' => '2026-07-12 08:28:00',
            ],
            // Post 4 (lunch) — liked by user 1 → likes_count = 1
            [
                'user_id' => 1,
                'likeable_type' => 'App\Models\Post',
                'likeable_id' => 4,
                'created_at' => '2026-07-12 09:19:13',
                'updated_at' => '2026-07-12 09:19:13',
            ],
            // Comment 1 ("awesome!") — liked by user 3 → likes_count = 1
            [
                'user_id' => 3,
                'likeable_type' => 'App\Models\Comment',
                'likeable_id' => 1,
                'created_at' => '2026-07-11 16:03:36',
                'updated_at' => '2026-07-11 16:03:36',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}