<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the oauth_access_tokens table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-07-12 09:25:14
 */
class OauthAccessTokensTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('oauth_access_tokens')->truncate();
        
        // Insert data in chunks
        DB::table('oauth_access_tokens')->insert([
            [
                'id' => '0965d918b33f74de82fcd5c5d2de354414025bcb4618b073a6b39872ec387518091668940e1201b2',
                'user_id' => 13,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 08:37:28',
                'updated_at' => '2026-07-12 08:37:28',
                'expires_at' => '2027-07-12 08:37:28',
            ],
            [
                'id' => '0e82a375115884ed8dc6407d64d612358e4a34514e6308f37449aa52c8c7fb6a6a810a420ef3624d',
                'user_id' => 9,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 08:21:53',
                'updated_at' => '2026-07-12 08:21:53',
                'expires_at' => '2027-07-12 08:21:53',
            ],
            [
                'id' => '10d0cb1eb427adb7f85e4a2a55d2682dc8d09652658e1816aba1c713ab0232262e02c83b4dfb6dad',
                'user_id' => 2,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 1,
                'created_at' => '2026-07-12 08:44:15',
                'updated_at' => '2026-07-12 09:17:27',
                'expires_at' => '2027-07-12 08:44:15',
            ],
            [
                'id' => '1ce36a96a8003c9e644a69fb8e84013de88b444e1c3a1587fd6864a1e94b9f6aef0a2fbb3bb09ca1',
                'user_id' => 8,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 08:21:15',
                'updated_at' => '2026-07-12 08:21:15',
                'expires_at' => '2027-07-12 08:21:15',
            ],
            [
                'id' => '274bead37008a964f592d057cc044ab6ed0bd4aa9bf510ed9ed47de0446c48084f7d4d7b8acf615a',
                'user_id' => 10,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 08:34:33',
                'updated_at' => '2026-07-12 08:34:33',
                'expires_at' => '2027-07-12 08:34:33',
            ],
            [
                'id' => '38c29bb641738eda3f3f291d8f2f84a3aa6a6450886bf2c94d7b40a39bcfe7968bf55d1e0ae88798',
                'user_id' => 1,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-11 15:07:01',
                'updated_at' => '2026-07-11 15:07:01',
                'expires_at' => '2027-07-11 15:07:01',
            ],
            [
                'id' => '464694b1e9b202c31414d5795ad25d90d52e6771da2e93b3fb9a1a8e27dbc45d2e69d46a1ccf453f',
                'user_id' => 5,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 1,
                'created_at' => '2026-07-11 16:04:44',
                'updated_at' => '2026-07-11 16:04:45',
                'expires_at' => '2027-07-11 16:04:44',
            ],
            [
                'id' => '56507c549d773de29f069b23148387681d4d0e514afe3740dc5693149be28bd34f50e71100a308a2',
                'user_id' => 2,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-11 15:04:52',
                'updated_at' => '2026-07-11 15:04:52',
                'expires_at' => '2027-07-11 15:04:52',
            ],
            [
                'id' => '56d637e1a9e5b052c580f5df8c1f2470ad429482fbfd7e99dc5fc93256af65157380afdbc3d05789',
                'user_id' => 12,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 08:36:52',
                'updated_at' => '2026-07-12 08:36:52',
                'expires_at' => '2027-07-12 08:36:52',
            ],
            [
                'id' => '5b43e909c99b196806465e237e03a044c26eab74d5c4619ab2fd1000286b4596f907c6e7beb270c6',
                'user_id' => 6,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 07:32:51',
                'updated_at' => '2026-07-12 07:32:51',
                'expires_at' => '2027-07-12 07:32:51',
            ],
            [
                'id' => '64e2b112392806ef4cf9e5610c78d8d304d1f8604a97a88fa44950378a55681b635831bc164fb4fa',
                'user_id' => 1,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-11 15:40:36',
                'updated_at' => '2026-07-11 15:40:36',
                'expires_at' => '2027-07-11 15:40:36',
            ],
            [
                'id' => '6a9f66f1b4712a800e4e07db08b777457dea93f6518a11b44bd4edbf801ec8f4cf375c0f8a8edd57',
                'user_id' => 1,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 1,
                'created_at' => '2026-07-12 08:32:37',
                'updated_at' => '2026-07-12 08:43:37',
                'expires_at' => '2027-07-12 08:32:37',
            ],
            [
                'id' => '92129f8159890ddf863c2ff66832a5649dccba554cc00cf933b29da3e8949eb4a95134e5d84fc301',
                'user_id' => 1,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 1,
                'created_at' => '2026-07-12 09:17:35',
                'updated_at' => '2026-07-12 09:22:35',
                'expires_at' => '2027-07-12 09:17:35',
            ],
            [
                'id' => '98ba8307678967d96a49b334bc1fe95b58fc194361faced00be503638432f57d11d2bfdc3c1343e1',
                'user_id' => 3,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 1,
                'created_at' => '2026-07-11 16:02:45',
                'updated_at' => '2026-07-11 16:04:07',
                'expires_at' => '2027-07-11 16:02:45',
            ],
            [
                'id' => 'a01d4bb8a0c994b35c71d49691f1aa8886c00166306d9db6f9a5dd23a3b1b64f3a32b08fa8ebe382',
                'user_id' => 1,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 07:21:55',
                'updated_at' => '2026-07-12 07:21:56',
                'expires_at' => '2027-07-12 07:21:55',
            ],
            [
                'id' => 'af346db6ef1894ad1521e7f8eae5c69cb541f44e77c103f6f8f144bfc4ed39cd02423569d99b7c74',
                'user_id' => 11,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 08:36:13',
                'updated_at' => '2026-07-12 08:36:13',
                'expires_at' => '2027-07-12 08:36:13',
            ],
            [
                'id' => 'b54d6064ae092583de664e437ba505b164bac2e8ec4ccde2d25908842805898bbe2c00df825d799e',
                'user_id' => 4,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-11 16:03:37',
                'updated_at' => '2026-07-11 16:03:37',
                'expires_at' => '2027-07-11 16:03:37',
            ],
            [
                'id' => 'c86a322a3694463432aad525a39e32a6373336f138e6c62152d85af6881ac40be433eb1a69d22d91',
                'user_id' => 7,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 08:20:41',
                'updated_at' => '2026-07-12 08:20:41',
                'expires_at' => '2027-07-12 08:20:41',
            ],
            [
                'id' => 'd44af8c8298ef372209aacab73f3b17e014dd14fdc3751fafbb74c8a69564efc3e3425b280b5fad1',
                'user_id' => 6,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 1,
                'created_at' => '2026-07-12 08:18:35',
                'updated_at' => '2026-07-12 08:32:29',
                'expires_at' => '2027-07-12 08:18:35',
            ],
            [
                'id' => 'e1232f17594cc084e36cad8ba618cd8b054acc5fb659eb62520761d10bbd660509f7843e71287240',
                'user_id' => 1,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-11 09:53:11',
                'updated_at' => '2026-07-11 09:53:11',
                'expires_at' => '2027-07-11 09:53:11',
            ],
            [
                'id' => 'fef66aa2de51f475f4655a53732c0c8252a5b08b205d54e66514c7b3d19ef4eda5b91a21dd45d0cb',
                'user_id' => 1,
                'client_id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'name' => 'auth_token',
                'scopes' => '[]',
                'revoked' => 0,
                'created_at' => '2026-07-12 09:22:41',
                'updated_at' => '2026-07-12 09:22:41',
                'expires_at' => '2027-07-12 09:22:41',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}