<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the oauth_clients table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-07-12 09:25:14
 */
class OauthClientsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('oauth_clients')->truncate();
        
        // Insert data in chunks
        DB::table('oauth_clients')->insert([
            [
                'id' => '019f5098-53e2-7368-a9e0-05aafeeeb70f',
                'owner_type' => null,
                'owner_id' => null,
                'name' => 'AppifyBook',
                'secret' => '$2y$12$6NvPeA6O304BG6DZwB7DrOo2ARYX.mGaCcy08xWs3GV9z27KyqB4m',
                'provider' => 'users',
                'redirect_uris' => '[]',
                'grant_types' => '["personal_access"]',
                'revoked' => 0,
                'created_at' => '2026-07-11 09:53:08',
                'updated_at' => '2026-07-11 09:53:08',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}