<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the posts table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-07-12 09:25:14
 */
class PostsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('posts')->truncate();
        
        // Insert data in chunks
        DB::table('posts')->insert([
            [
                'id' => 1,
                'user_id' => 3,
                'content' => 'secret',
                'image_path' => null,
                'visibility' => 'private',
                'likes_count' => 0,
                'comments_count' => 0,
                'created_at' => '2026-07-11 16:03:07',
                'updated_at' => '2026-07-11 16:03:07',
            ],
            [
                'id' => 2,
                'user_id' => 6,
                'content' => 'it\'s breakfast time!',
                'image_path' => 'posts/UO77rs23F2fI16WiPi5ubwfkvAzgXZYVbChkkKb2.png',
                'visibility' => 'public',
                'likes_count' => 2,
                'comments_count' => 1,
                'created_at' => '2026-07-12 08:29:08',
                'updated_at' => '2026-07-12 09:19:13',
            ],
            [
                'id' => 3,
                'user_id' => 1,
                'content' => 'The fresh moment of the sunrise. I love that.',
                'image_path' => 'posts/ITmbR1lFftcTUVyd2jirRyIJrvLadQYQeC4ziB6j.png',
                'visibility' => 'public',
                'likes_count' => 1,
                'comments_count' => 1,
                'created_at' => '2026-07-12 08:33:54',
                'updated_at' => '2026-07-12 09:18:29',
            ],
            [
                'id' => 4,
                'user_id' => 2,
                'content' => 'It\'s Lunch time!!!!',
                'image_path' => 'posts/5Od1ca7yI3FZmOK4FUMqKS79141mMcmeo8x1IL3P.png',
                'visibility' => 'public',
                'likes_count' => 1,
                'comments_count' => 1,
                'created_at' => '2026-07-12 08:44:47',
                'updated_at' => '2026-07-12 09:18:13',
            ],
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}