<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

/**
 * Seeder class for the users table.
 * Generated by Laravel DB Craft.
 * Generated on: 2026-07-12 09:25:14
 */
class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Disable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate the table
        DB::table('users')->truncate();

        // Insert data in chunks
        DB::table('users')->insert([
            [
                'id' => 1,
                'first_name' => 'MsM',
                'last_name' => 'Robin',
                'email' => 'msmrobin518@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$czpw5JKJrH0JuRHBkE6pGeculVuw24IBiSlgMNxRU9gmpbXi5mNee',
                'avatar' => null,
                'remember_token' => null,
                'created_at' => '2026-07-11 09:53:11',
                'updated_at' => '2026-07-11 09:53:11',
            ],
            [
                'id' => 2,
                'first_name' => 'Kamal',
                'last_name' => 'Khan',
                'email' => 'kamalkhan@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$2wGtlqGHWjX9Ki0rKa2HTOtB/W8NHhUe/6NY1qp.42vFkGjYry/ty',
                'avatar' => null,
                'remember_token' => null,
                'created_at' => '2026-07-11 15:04:43',
                'updated_at' => '2026-07-11 15:04:43',
            ],
            [
                'id' => 3,
                'first_name' => 'Alice',
                'last_name' => 'Wonder',
                'email' => 'alice_1783785763@test.com',
                'email_verified_at' => null,
                'password' => '$2y$12$FefGhVewvs8p1wgqhDoEieCY/txcNhCIoglObgAc3cUWJ28bsv5p6',
                'avatar' => 'avatars/avatar_3.png',
                'remember_token' => null,
                'created_at' => '2026-07-11 16:02:44',
                'updated_at' => '2026-07-11 16:02:44',
            ],
            [
                'id' => 4,
                'first_name' => 'Bob',
                'last_name' => 'Builder',
                'email' => 'bob_1783785816@test.com',
                'email_verified_at' => null,
                'password' => '$2y$12$gZcv00k.Ej.VjkY0ReYBpeLgFFFn3hiuypOEpKHxFc.YscXLZSsKy',
                'avatar' => 'avatars/avatar_4.png',
                'remember_token' => null,
                'created_at' => '2026-07-11 16:03:37',
                'updated_at' => '2026-07-11 16:03:37',
            ],
            [
                'id' => 5,
                'first_name' => 'Carol',
                'last_name' => 'Danvers',
                'email' => 'carol_1783785883@test.com',
                'email_verified_at' => null,
                'password' => '$2y$12$5daLTJ3BzshOFf62rttEbuWK13rq8x3MdnVz5bZBSkiUiOa1DIN0m',
                'avatar' => 'avatars/avatar_5.png',
                'remember_token' => null,
                'created_at' => '2026-07-11 16:04:44',
                'updated_at' => '2026-07-11 16:04:44',
            ],
            [
                'id' => 6,
                'first_name' => 'Jannatul',
                'last_name' => 'Tania',
                'email' => 'tania@gmail.com',
                'email_verified_at' => null,
                'password' => '$2y$12$p2J2xlmxn/1OUfKVKRBUAe2ipU4eww0A4rNvbUaqJsTLfmMFZoTfS',
                'avatar' => 'avatars/avatar_6.png',
                'remember_token' => null,
                'created_at' => '2026-07-12 07:32:44',
                'updated_at' => '2026-07-12 07:32:49',
            ]
        ]);
        
        // Re-enable foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}